import type { RuntimeLanguage } from "../ir/index.js";

export const WORKFLOW_PATH = ".github/workflows/flareon.yml";

export interface WorkflowOptions {
  runtime: RuntimeLanguage;
  /** push で deploy する永続ブランチ（GitHub の branches フィルタのパターン）。 */
  branches: string[];
}

const q = (s: string): string => (/^[A-Za-z0-9_./*-]+$/.test(s) ? s : JSON.stringify(s));

/**
 * GitHub Actions ワークフロー雛形。
 * - push（永続ブランチ）→ deploy、PR の opened/synchronize/reopened → preview deploy、closed → destroy
 * - AWS へは OIDC（長期アクセスキーなし）。ロール ARN とリージョンはリポジトリ変数
 * - Flareon は未公開のため、インストール元は FLAREON_PACKAGE（リポジトリ変数で上書き可）で指定する
 */
export function workflowTemplate({ runtime, branches }: WorkflowOptions): string {
  const install =
    runtime === "typescript"
      ? `
      - name: Install app dependencies
        working-directory: app
        run: npm install --no-audit --no-fund
`
      : "";
  const awsSteps = `      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
${install}
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: \${{ vars.FLAREON_AWS_ROLE_ARN }}
          aws-region: \${{ vars.FLAREON_AWS_REGION }}
`;
  return `# Generated by flareon init. Setup: flareon bootstrap github --repo <owner>/<name>
name: Flareon

on:
  push:
    branches: [${branches.map(q).join(", ")}]
  pull_request:
    types: [opened, synchronize, reopened, closed]

# AWS access uses OIDC (no long-lived keys). pull-requests/deployments: preview URL comment and Deployment status.
permissions:
  id-token: write
  contents: read
  pull-requests: write
  deployments: write

# One run at a time per pull request (or branch); never cancel a deploy halfway.
concurrency:
  group: flareon-\${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  # Flareon is not published to npm yet. Set the repository variable FLAREON_PACKAGE
  # (e.g. a tarball URL or git spec) to install it from elsewhere.
  FLAREON_PACKAGE: \${{ vars.FLAREON_PACKAGE || 'flareon@latest' }}

jobs:
  deploy:
    # Not for closed PRs, and not for forks (they get neither OIDC nor secrets).
    if: >-
      github.event_name == 'push' ||
      (github.event.action != 'closed' &&
       github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    steps:
${awsSteps}
      - name: Deploy
        id: deploy
        run: npx --yes "$FLAREON_PACKAGE" deploy --ci

      - name: Report to GitHub
        if: \${{ !cancelled() }}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: npx --yes "$FLAREON_PACKAGE" github comment --state \${{ steps.deploy.outcome == 'success' && 'success' || 'failure' }}

  destroy:
    if: >-
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
${awsSteps}
      - name: Destroy preview
        run: npx --yes "$FLAREON_PACKAGE" destroy --ci

      - name: Report to GitHub
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: npx --yes "$FLAREON_PACKAGE" github comment --state inactive
`;
}
